country_start = [
    "Italy",
    "France",
    "Germany",
    "Spain",
    "Portugal",
    "Switzerland",
    "Belgium",
    "Netherlands",
]

countries = [
    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Vatican City",
]

european_cities = {
    "Italy": [
        "Rome",
        "Milan",
        "Naples",
        "Florence",
        "Bologna",
        "Bari",
        "Genova",
        "Palermo",
        "Turin",
        "Venice",
        "Verona",
    ],
    "France": [
        "Paris",
        "Marseille",
        "Lyon",
        "Strasbourg",
        "Toulouse",
        "Lille",
        "Nantes",
    ],
    "Germany": [
        "Berlin",
        "Munich",
        "Hamburg",
        "Cologne",
        "Frankfurt",
        "Stuttgart",
        "Nuremberg",
        "Liepzig",
        "Dusseldorf",
    ],
    "Austria": ["Vienna", "Graz", "Linz", "Innsbruck", "Klagenfurt"],
    "Spain": [
        "Madrid",
        "Barcelona",
        "Valencia",
        "Seville",
        "Bilbao",
        "Malaga",
        "Zaragoza",
    ],
    "Portugal": ["Lisbon", "Porto", "Faro", "Coimbra"],
    "Switzerland": ["Zurig", "Basel", "Lugano"],
    "Belgium": ["Brussels", "Ghent"],
    "Netherlands": ["Amsterdam", "Rotterdam", "Utrecht"],
    # Add more countries and cities as needed
}

night_jets = {
    "Austria": ["Vienna", "Salisburgo", "Linz", "Graz", "Innsbruck"],
    "Switzerland": ["Zurich", "Basel"],
    "Germany": [
        "Hamburg",
        "Berlin",
        "Cologne",
        "Frankfurt",
        "Düsseldorf",
        "Munich",
        "Stuttgart",
    ],
    "Italy": [
        "Florence",
        "Rome",
        "Verona",
        "Lake Garda",
        "Milan",
        "Venice",
        "Bologna",
        "Genoa",
        "La Spezia & Cinque Terre",
    ],
    "Belgium": ["Brussels"],
    "Netherlands": ["Amsterdam", "Utrecht"],
    "France": ["Paris", "Strasbourg"],
    "Croatia": ["Zagreb", "Split"],
}

price_ranges = [
    "Up to 500 €",
    "500-1000€",
    "1000-1500 €",
    "Up to 2000 €",
    "More than 2000€",
]
